
from __future__ import annotations

import os
from typing import Optional


def _env(name: str, default: str) -> str:
    val = os.environ.get(name)
    return val if val is not None and val != "" else default



HOT_LIMIT_MB = 500


WARM_LIMIT_MB = 2000
ALLOW_CAP = False
NDJSON_TRIM_INTERVAL = 0


TASK_ORDER = _env("SLIMTOKEN_MEMORY_TASK_ORDER", "queued")


MAX_TASK_QUEUE = int(_env("SLIMTOKEN_MEMORY_MAX_TASK_QUEUE", "10000"))
SCHEDULER_TICK_SECONDS = float(_env("SLIMTOKEN_MEMORY_SCHEDULER_TICK", "0.5"))


DISTILLER_INTERVAL_SECONDS = int(_env("SLIMTOKEN_MEMORY_DISTILL_INTERVAL", "1800"))
DISTILLER_MIN_CONFIDENCE = float(_env("SLIMTOKEN_MEMORY_DISTILL_MIN_CONF", "0.5"))
DISTILLER_PLATFORM = _env("SLIMTOKEN_MEMORY_DISTILL_PLATFORM", "")



HOOK_WRITE_TIERS = ("hot",)
HOOK_ATOMIC = True
HOOK_RETRIES = 1




HOT_SUBDIR = _env("SLIMTOKEN_MEMORY_HOT_SUBDIR", "hot")



WARM_SUBDIR = _env("SLIMTOKEN_MEMORY_WARM_SUBDIR", "warm")
COLD_SUBDIR = _env("SLIMTOKEN_MEMORY_COLD_SUBDIR", "cold")


def describe() -> dict:

    return {
        "HOT_LIMIT_MB": HOT_LIMIT_MB,
        "ALLOW_CAP": ALLOW_CAP,
        "TASK_ORDER": TASK_ORDER,
        "MAX_TASK_QUEUE": MAX_TASK_QUEUE,
        "SCHEDULER_TICK_SECONDS": SCHEDULER_TICK_SECONDS,
        "DISTILLER_INTERVAL_SECONDS": DISTILLER_INTERVAL_SECONDS,
        "DISTILLER_MIN_CONFIDENCE": DISTILLER_MIN_CONFIDENCE,
        "HOOK_WRITE_TIERS": HOOK_WRITE_TIERS,
        "HOOK_ATOMIC": HOOK_ATOMIC,
    }


__all__ = [
    "HOT_LIMIT_MB", "WARM_LIMIT_MB", "ALLOW_CAP", "NDJSON_TRIM_INTERVAL",
    "TASK_ORDER", "MAX_TASK_QUEUE", "SCHEDULER_TICK_SECONDS",
    "DISTILLER_INTERVAL_SECONDS", "DISTILLER_MIN_CONFIDENCE", "DISTILLER_PLATFORM",
    "HOOK_WRITE_TIERS", "HOOK_ATOMIC", "HOOK_RETRIES",
    "HOT_SUBDIR", "WARM_SUBDIR", "COLD_SUBDIR",
    "describe",
]